services:
  db:
    image: pgvector/pgvector:0.8.0-pg16-trixie
    container_name: pgvector-db
    environment:
      POSTGRES_USER: raymolin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: test
    command: postgres -c 'shared_buffers=2GB'
    shm_size: 4g
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/data/pgvector
    deploy:
      resources:
        limits:
          cpus: ${CPU:-4}
          memory: ${MEMORY:-16G}
volumes:
  pgdata:
